name: Thisaquaticlife.com
favicon: null
layout_spectrum: 0.9345
typography_spectrum: 0.2341
title: ThisAquaticLife.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-47021812-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#333333'
    - '#4d4d4d'
    - '#b7b7b7'
    - '#909090'
    - '#696969'
  brandStrength: 0.5
  lightness: 0.25
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
