name: Thisaquaticlife.com
favicon: null
layout_spectrum: 0
typography_spectrum: 0
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#053569'
    - '#0e64b0'
    - '#5d5759'
    - '#777374'
    - '#313746'
  brandStrength: 0.5
  lightness: 0.3248397377319634
  saturation: 0.6056109718047082
  rhythmicContrast: 0.3304509927984327
purpose: []
