name: Thisaquaticlife.com
favicon: null
layout_spectrum: 0.25819
typography_spectrum: 0.2341
title: ThisAquaticLife.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-47021812-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#141414'
    - '#9f9f9f'
    - '#454545'
    - '#c7c7c7'
  brandStrength: 0.5
  lightness: 0.4375
  saturation: 0.5625
  rhythmicContrast: 0.25
purpose: []
